pipeline{

 agent any
   tools{
    maven 'Maven_Home'
        } 
  stages{
    stage('Build'){
     steps{
      sh 'mvn -f trucks/pom.xml clean install package'     
     }
    post{
      success{
        echo "Archiving the Artifacts"
        archiveArtifacts artifacts: '**/target/*.war'
        }   
      }
   }
  
 stage('deploy to tomcat server'){
  steps{
   deploy adapters: [tomcat9(credentialsId: 'e0d5dcea-fca3-4114-a7c9-f3031793c003', path: '', url: 'http://3.86.77.115:8090/')], contextPath: null, war: '**/*.war'
     }
   }
 }
}
